import type { Product } from "./types";

type SeedProduct = Omit<Product, "createdAt" | "updatedAt" | "imageKey">;

export const seedProducts: SeedProduct[] = [
  {
    id: "p-cookie-nutella",
    name: "کوکی نوتلا",
    slug: "cookie-nutella",
    description:
      "کوکی کره‌ای با مغز کرم نوتلا، شکلات چیپسی و بافت نرم و کش‌دار.",
    price: 135000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-nutella.png",
    stockQty: 50,
    active: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "p-cookie-lotus",
    name: "کوکی لوتوس",
    slug: "cookie-lotus",
    description:
      "کوکی کره‌ای با کرم و بیسکویت لوتوس؛ طعمی کاراملی و دل‌نشین.",
    price: 135000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-lotus.png",
    stockQty: 50,
    active: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "p-cookie-double-chocolate",
    name: "کوکی دبل چاکلت",
    slug: "cookie-double-chocolate",
    description:
      "کوکی شکلاتی با کاکائو و تکه‌های شکلات تلخ؛ انتخابی غلیظ برای عاشقان شکلات.",
    price: 125000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-double-chocolate.png",
    stockQty: 50,
    active: true,
    featured: true,
    sortOrder: 3,
  },
  {
    id: "p-cookie-pistachio",
    name: "کوکی پسته",
    slug: "cookie-pistachio",
    description:
      "کوکی کره‌ای پسته با مغز کرم پسته و شکلات سفید؛ خوش‌عطر و پریمیوم.",
    price: 145000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-pistachio.png",
    stockQty: 40,
    active: true,
    featured: true,
    sortOrder: 4,
  },
  {
    id: "p-cookie-diet",
    name: "کوکی رژیمی",
    slug: "cookie-diet",
    description:
      "کوکی بادام‌زمینی و جو دوسر پرک با شیرین‌کننده بدون قند؛ سبک و خوش‌طعم.",
    price: 85000,
    category: "cookie",
    weightLabel: "۶۰ گرم",
    imageUrl: "/products/cookie-diet.png",
    stockQty: 40,
    active: true,
    featured: false,
    sortOrder: 5,
  },
  {
    id: "p-jar-pistachio-milk",
    name: "جارکیک سه‌شیر پسته",
    slug: "pistachio-three-milk-jar",
    description:
      "لایه‌های لطیف کیک سه‌شیر، خامه و تکه‌های پسته؛ مرطوب و مناسب یک نفر.",
    price: 195000,
    category: "jar",
    weightLabel: "۲۰۰ سی‌سی",
    imageUrl: "/products/jar-pistachio-milk.png",
    stockQty: 25,
    active: true,
    featured: false,
    sortOrder: 6,
  },
  {
    id: "p-jar-chocolate",
    name: "جارکیک شکلاتی",
    slug: "chocolate-jar-cake",
    description:
      "کیک اسفنجی شکلاتی با خامه شکلاتی و چیپس شکلات؛ کلاسیک و عمیق.",
    price: 175000,
    category: "jar",
    weightLabel: "۲۰۰ سی‌سی",
    imageUrl: "/products/jar-chocolate.png",
    stockQty: 25,
    active: true,
    featured: false,
    sortOrder: 7,
  },
  {
    id: "p-jar-tiramisu",
    name: "جارکیک تیرامیسو",
    slug: "tiramisu-jar-cake",
    description:
      "لیدی‌فینگر آغشته به قهوه، کرم تیرامیسو و پودر کاکائو؛ الهام‌گرفته از دسر ایتالیایی.",
    price: 180000,
    category: "jar",
    weightLabel: "۲۰۰ سی‌سی",
    imageUrl: "/products/jar-tiramisu.png",
    stockQty: 25,
    active: true,
    featured: false,
    sortOrder: 8,
  },
  {
    id: "p-blondie-apple-cinnamon",
    name: "بلوندی سیب و دارچین",
    slug: "apple-cinnamon-blondie",
    description:
      "بلوندی کره‌ای با سیب تازه و دارچین؛ گرم، معطر و مناسب کنار قهوه.",
    price: 165000,
    category: "cake",
    weightLabel: "اسلایس",
    imageUrl: "/products/blondie-apple-cinnamon.png",
    stockQty: 20,
    active: true,
    featured: false,
    sortOrder: 9,
  },
  {
    id: "p-carrot-walnut-cake",
    name: "کیک هویج و گردو",
    slug: "carrot-walnut-cake",
    description:
      "کیک نرم و مرطوب با هویج تازه و گردو؛ انتخابی کلاسیک و محبوب.",
    price: 125000,
    category: "cake",
    weightLabel: "اسلایس",
    imageUrl: "/products/carrot-walnut-cake.png",
    stockQty: 20,
    active: true,
    featured: false,
    sortOrder: 10,
  },
];
