import type { Product } from "./types";

type SeedProduct = Omit<Product, "createdAt" | "updatedAt" | "imageKey">;

export const seedProducts: SeedProduct[] = [
  {
    id: "p-cookie-nutella",
    name: "کوکی نوتلا",
    slug: "cookie-nutella",
    description:
      "کوکی کره‌ای با مغز کرم نوتلا، کره نیوزیلندی، شکر قهوه‌ای وارداتی و شکلات چیپسی؛ انتخابی پرفروش برای ویترین کافه.",
    price: 135000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-nutella.webp",
    stockQty: 200,
    active: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "p-cookie-lotus",
    name: "کوکی لوتوس",
    slug: "cookie-lotus",
    description:
      "کوکی کره‌ای با کرم و بیسکویت لوتوس، کره نیوزیلندی و شکر قهوه‌ای وارداتی؛ با طعم کارامل و بافتی دلپذیر.",
    price: 135000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-lotus.webp",
    stockQty: 200,
    active: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "p-cookie-double-chocolate",
    name: "کوکی دبل چاکلت",
    slug: "cookie-double-chocolate",
    description:
      "کوکی شکلاتی با کره نیوزیلندی، شکر قهوه‌ای وارداتی، پودر کاکائوی ترک و هلندی و تکه‌های شکلات تلخ.",
    price: 125000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-double-chocolate.webp",
    stockQty: 200,
    active: true,
    featured: true,
    sortOrder: 3,
  },
  {
    id: "p-cookie-pistachio",
    name: "کوکی پسته",
    slug: "cookie-pistachio",
    description:
      "کوکی کره‌ای پسته با تکه‌های پسته، مغز کرم پسته و شکلات سفید؛ انتخابی پریمیوم و چشم‌نواز برای ویترین.",
    price: 145000,
    category: "cookie",
    weightLabel: "۹۰ گرم",
    imageUrl: "/products/cookie-pistachio.webp",
    stockQty: 200,
    active: true,
    featured: true,
    sortOrder: 4,
  },
  {
    id: "p-cookie-diet",
    name: "کوکی رژیمی",
    slug: "cookie-diet",
    description:
      "کوکی با کره بادام‌زمینی، بادام پرک، آرد جو و جو دوسر پرک با شیرین‌کننده بدون قند استویا.",
    price: 85000,
    category: "cookie",
    weightLabel: "۶۰ گرم",
    imageUrl: "/products/cookie-diet.webp",
    stockQty: 200,
    active: true,
    featured: false,
    sortOrder: 5,
  },
  {
    id: "p-jar-pistachio-milk",
    name: "جارکیک سه‌شیر پسته",
    slug: "pistachio-three-milk-jar",
    description:
      "لایه‌های لطیف کیک سه‌شیر آغشته به شیر عسلی، خامه و تکه‌های پسته؛ مرطوب، غنی و آماده سرو تک‌نفره.",
    price: 195000,
    category: "jar",
    weightLabel: "۲۰۰ سی‌سی",
    imageUrl: "/products/jar-pistachio-milk.webp",
    stockQty: 200,
    active: true,
    featured: false,
    sortOrder: 6,
  },
  {
    id: "p-jar-chocolate",
    name: "جارکیک شکلاتی",
    slug: "chocolate-jar-cake",
    description:
      "لایه‌های کیک اسفنجی شکلاتی، خامه شکلاتی و چیپس شکلات؛ طعمی عمیق با بافت خامه‌ای متعادل.",
    price: 175000,
    category: "jar",
    weightLabel: "۲۰۰ سی‌سی",
    imageUrl: "/products/jar-chocolate.webp",
    stockQty: 200,
    active: true,
    featured: false,
    sortOrder: 7,
  },
  {
    id: "p-jar-tiramisu",
    name: "جارکیک تیرامیسو",
    slug: "tiramisu-jar-cake",
    description:
      "لیدی‌فینگر آغشته به قهوه، کرم تیرامیسو و پودر کاکائوی ترک و هلندی؛ الهام‌گرفته از دسر کلاسیک ایتالیایی.",
    price: 180000,
    category: "jar",
    weightLabel: "۲۰۰ سی‌سی",
    imageUrl: "/products/jar-tiramisu.webp",
    stockQty: 200,
    active: true,
    featured: false,
    sortOrder: 8,
  },
  {
    id: "p-blondie-apple-cinnamon",
    name: "بلوندی سیب و دارچین",
    slug: "apple-cinnamon-blondie",
    description:
      "بلوندی کره‌ای با کره نیوزیلندی، شکر قهوه‌ای وارداتی، تکه‌های سیب تازه و دارچین؛ مناسب همراهی با قهوه و چای.",
    price: 165000,
    category: "cake",
    weightLabel: "اسلایس",
    imageUrl: "/products/blondie-apple-cinnamon.webp",
    stockQty: 200,
    active: true,
    featured: false,
    sortOrder: 9,
  },
  {
    id: "p-carrot-walnut-cake",
    name: "کیک هویج و گردو",
    slug: "carrot-walnut-cake",
    description:
      "کیک نرم، مرطوب و خوش‌عطر با هویج تازه و گردوی مرغوب؛ انتخابی کلاسیک و محبوب برای ویترین.",
    price: 125000,
    category: "cake",
    weightLabel: "اسلایس",
    imageUrl: "/products/carrot-walnut-cake.webp",
    stockQty: 200,
    active: true,
    featured: false,
    sortOrder: 10,
  },
];
